DEFINE INPUT  PARAMETER vc-filename AS CHARACTER   NO-UNDO.
DEFINE OUTPUT PARAMETER vl-v6frame  AS LOGICAL     NO-UNDO.

DEFINE VARIABLE vc-file     AS LONGCHAR    NO-UNDO.

COPY-LOB FROM FILE vc-filename TO vc-file.

IF vc-file MATCHES '*V6FRAME*' THEN
   ASSIGN vl-v6frame = YES.

